{{- if .Values.istio.enabled -}}
{{- $fullName := include "base.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $fullName }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: {{ $svcPort }}
      name: tcp
      protocol: TCP
    hosts:
    - {{ .Values.istio.host | quote }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  hosts:
  - {{ .Values.istio.host | quote }}
  gateways:
  - {{ $fullName }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.path }}
    route:
    - destination:
        port:
          number: {{ $svcPort }}
        host: {{ $fullName }}
{{- end }}
