{{- if .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "base.fullname" . }}
    labels:
  {{ include "base.labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}